import json
import os

GENERAL_QUERIES = [
    "How many students are currently enrolled in UCSI?",
    "What is the total number of lecturers?",
    "Tell me about the history of UCSI University.",
    "Is UCSI ranked in the top 100 universities?",
    "What are the main campus facilities?",
    "Do you offer online degrees?",
    "How many faculties are there?",
    "What is the vision of UCSI?",
    "Who is the founder of UCSI?",
    "Is there a swimming pool on campus?",
    "Can I apply for a scholarship?",
    "What is the acceptance rate?",
    "Do you have exchange programs?",
    "Is there a gym for students?",
    "What are the library opening hours?",
    "How many international students are there?",
    "What is the average class size?",
    "Do you have a career center?",
    "Is there on-campus housing?",
    "What sports clubs are available?",
    "How do I apply for a student visa?",
    "Is there a shuttle bus service?",
    "What are the English requirements?",
    "Can I work part-time while studying?",
    "What is the cost of living in Kuala Lumpur?",
    "Do you offer Ph.D. programs?",
    "Is there a counseling service?",
    "What is the dress code?",
    "Are there prayer rooms?",
    "Is there a cafeteria?",
    "How far is the campus from the city center?",
    "What is the climate like?",
    "Do you have a music program?",
    "Is there a medical center?",
    "What is the grading system?",
    "Can I change my major?",
    "Is there a student union?",
    "What are the parking fees?",
    "Do you have a debate club?",
    "Is there a robotics lab?",
    "What is the deadline for application?",
    "Do you accept transfer students?",
    "Is there a mentorship program?",
    "What are the alumni benefits?",
    "Do you have a law school?",
    "Is there a dedicated art studio?",
    "What is the student-to-faculty ratio?",
    "Do you have a psychology clinic?",
    "Is there a pharmacy on campus?",
    "What are the IT support hours?",
    "Do you offer summer courses?",
    "Is there a language center?",
    "What is the refund policy?",
    "Do you have a startup incubator?",
    "Is there a 3D printing lab?",
    "What are the safety measures on campus?",
    "Do you have a vast alumni network?",
    "Is there a dedicated research center?",
    "What are the key research areas?",
    "Do you have industry partnerships?",
    "Is there an internship program?",
    "What are the key values of UCSI?",
    "Do you have a sustainability initiative?",
    "Is there a volunteer program?",
    "What are the major events on campus?",
    "Do you strictly follow a semester system?",
    "Is there a graduation ceremony every year?",
    "What are the popular student hangouts?",
    "Do you have a digital library?",
    "Is there a mobile app for students?",
    "What are the key achievements of UCSI?",
    "Do you have a Nobel laureate among alumni?",
    "Is there a specific uniform?",
    "What are the nearby attractions?",
    "Do you have a strict attendance policy?",
    "Is there a disability support service?",
    "What are the key accreditation bodies?",
    "Do you have a double degree program?",
    "Is there a pathways program?",
    "What are the key partner universities?",
    "Do you have a strong engineering faculty?",
    "Is there a dedicated architecture studio?",
    "What are the key medical programs?",
    "Do you have a hospitality school?",
    "Is there a fashion design program?",
    "What are the key business majors?",
    "Do you have a mass communication program?",
    "Is there a psychology major?",
    "What are the key science programs?",
    "Do you have a music conservatory?",
    "Is there a pharmacy program?",
    "What are the key computer science majors?",
    "Do you have an actuarial science program?",
    "Is there an optometry program?",
    "What are the key nutrition programs?",
    "Do you have an aquatic science program?",
    "Is there a biotechnology program?",
    "What are the key food science programs?",
    "Do you have a marine science program?"
]

RAG_QUERIES = [
    "Tell me about Assistant Professor Zahrul Azmir",
    "Who is the Dean of Faculty of Applied Sciences?",
    "What is the email of Dr Crystale Lim Siew Ying?",
    "Where is Block A located?",
    "Show me the map of Block G",
    "What are the facilities in Block B?",
    "Tell me about the Computer Science programme",
    "How much is the tuition fee for Bachelor of Computer Science?",
    "Who is the lecturer for Mobile Application Development?",
    "What is the duration of the outcome based education workshop?",
    "Tell me about Assistant Professor Dr Michelle Soo Oi Yoon",
    "Who is the Head of Research in FSA?",
    "What is the email of Teo Swee Sen?",
    "Where is the library located?",
    "Show me the image of Block C",
    "What classes are held in Block D?",
    "Tell me about the Nursing programme",
    "How much is the hostel fee for single room with AC?",
    "Who is the course coordinator for CN101?",
    "What is the schedule for Dr. Thung?",
    "Tell me about Professor Dr Rogayah Bt A Razak",
    "Who is the Deputy Dean of FSSLA?",
    "What is the email of Hamedi Bin Mohd Adnan?",
    "Where is the exam hall?",
    "Show me the map of Block E",
    "What labs are in Block L?",
    "Tell me about the Music programme",
    "How much is the deposit for hostel?",
    "Who teaches structural analysis?",
    "What time is the class for CS101?",
    "Tell me about Assistant Professor Dr Anne Noor Sri Juwaneeta",
    "Who is the Head of Praxis in FSSLA?",
    "What is the email of Yam Hok Chai?",
    "Where is the student council office?",
    "Show me the image of the swimming pool",
    "What offices are in Block A?",
    "Tell me about the Pharmacy programme",
    "How much is the resource fee?",
    "Who is the program leader for IT?",
    "What is the consultation hour for Dr. Lau?",
    "Tell me about Assistant Professor Dr Lau Yin Yin",
    "Who is the Head of Department for Biotechnology?",
    "What is the email of Nadia Binti Samsudin?",
    "Where is the auditorium?",
    "Show me the map of the gym",
    "What shops are in Block G?",
    "Tell me about the Architecture programme",
    "How much is the orientation fee?",
    "Who is the lecturer for Data Structures?",
    "What is the venue for the Python workshop?",
    "Tell me about Assistant Professor Dr Othman Bin Talib",
    "Who is the Head of Programme for Applied Microbiology?",
    "What is the email of Othman Bin Talib?",
    "Where is the registrar office?",
    "Show me the image of the cafeteria",
    "What research centers are in Block C?",
    "Tell me about the Psychology programme",
    "How much is the international student fee?",
    "Who teaches Business Law?",
    "What is the schedule for the React class?",
    "Tell me about Assistant Professor Dr Ngerng Miang Hong",
    "Who is the Head of Programme for Biotechnology?",
    "What is the email of Ngerng Miang Hong?",
    "Where is the finance office?",
    "Show me the map of the parking lot",
    "What clinics are on campus?",
    "Tell me about the Optometry programme",
    "How much is the insurance fee?",
    "Who is the coordinator for Final Year Project?",
    "What time does the library close?",
    "Tell me about Assistant Professor Dr Tan Choon Hui",
    "Who is the Deputy Dean for Research?",
    "What is the email of Tan Choon Hui?",
    "Where is the international office?",
    "Show me the image of the library",
    "What labs are in Block B?",
    "Tell me about the Engineering programme",
    "How much is the visa processing fee?",
    "Who teaches Calculus?",
    "What is the room number for the Java lab?",
    "Tell me about Assistant Professor Dr Eu Kok Seng",
    "Who is the Head of Department for CS?",
    "What is the email of Eu Kok Seng?",
    "Where is the career center?",
    "Show me the map of the shuttle stop",
    "What banks are near campus?",
    "Tell me about the Hospitality programme",
    "How much is the late payment fee?",
    "Who is the lecturer for AI?",
    "What is the date for the next intake?",
    "Tell me about Assistant Professor Dr Rohana Binti Jani",
    "Who is the Head of Programme for Food Science?",
    "What is the email of Rohana Binti Jani?",
    "Where is the alumni office?",
    "Show me the image of the hostel",
    "What facilities are in the student center?",
    "Tell me about the Fashion programme",
    "How much is the graduation fee?",
    "Who teaches Marketing?",
    "What is the deadline for add/drop?"
]

def generate():
    os.makedirs("test_cases/generated", exist_ok=True)
    
    with open("test_cases/generated/general_queries.json", "w", encoding="utf-8") as f:
        json.dump(GENERAL_QUERIES, f, indent=2, ensure_ascii=False)
        print(f"Generated {len(GENERAL_QUERIES)} general queries.")

    with open("test_cases/generated/rag_queries.json", "w", encoding="utf-8") as f:
        json.dump(RAG_QUERIES, f, indent=2, ensure_ascii=False)
        print(f"Generated {len(RAG_QUERIES)} RAG queries.")

if __name__ == "__main__":
    generate()
